# Generated by Django 4.0.5 on 2022-06-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=40, verbose_name='Статус')),
                ('date', models.CharField(blank=True, max_length=40, null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
